# -*- coding: utf-8 -*-
"""
Created on Fri Apr 29 08:51:30 2022

@author: Santiago
"""
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGetResoluciones():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_getResoluciones(self):
    self.driver.get("http://gaceta.ces.gob.ec/inicio.html")
    self.driver.set_window_size(1346, 708)
    self.driver.find_element(By.ID, "j_idt43").click()
    self.driver.find_element(By.ID, "mensajeCes").click()
    self.driver.find_element(By.ID, "linkBusquedaAVA").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-seek-next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-seek-next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-seek-next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-seek-next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-seek-next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-seek-next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-seek-next").click()
  
